# Discussion: 8-paragraph argument (PAS → oral gap → triage → docking → MD → hypothesis → PAS pharmacology → limits).
# Keys = prefixes in current English backup / current Chinese body.
# Fact + [n]; no "Author et al. used"; no RMSD/SASA tables; first-appearance 38–54 preserved.

EN_REPLACE = {
    "AChE hydrolyses acetylcholine at cholinergic synapses.": (
        "AChE hydrolyses acetylcholine at cholinergic synapses. In AD tissue the same "
        "enzyme sits on amyloid plaques. AChE accelerates Aβ fibril growth through the "
        "PAS, and AChE–Aβ particles are more toxic than free peptide [4]. Stable "
        "enzyme–peptide complexes change AChE biochemistry and raise fibril "
        "neurotoxicity. Isolated complexes contain enzyme bound to growing fibrils "
        "[38–39]. A short hydrophobic PAS motif is sufficient for that chaperone effect "
        "[5]. A monoclonal antibody to AChE blocks the effect [40], and PAS-directed "
        "small molecules reach the same endpoint [6]. Excess AChE promotes cortical Aβ "
        "plaques in mice [41]. Reviews of AChE in AD place plaque-associated enzyme in "
        "cross-talk with Aβ and phospho-tau, and the plaque-associated activity remains "
        "sensitive to PAS blockade [42–44]. Hippocampal AChE–Aβ complexes produce more "
        "damage than free fibrils [45]. The PAS maps to Tyr72, Asp74, Tyr124, Trp286 "
        "and Tyr341, about 20 Å from the catalytic triad at the gorge mouth [46]. These "
        "studies support PAS as a functional surface that can take part in "
        "AChE-mediated Aβ assembly [2–3]. The present docking and 100-ns trajectories "
        "examine predicted contacts of periodontitis-derived micropeptides at that "
        "surface."
    ),
    "An oral exposure path is documented at the organism": (
        "An oral exposure path is documented at the organism and protease level. "
        "Periodontopathic virulence factors have been detected in short-term postmortem "
        "AD brain [47]. P. gingivalis and gingipains have been reported in AD brains, "
        "and oral infection in mice raises brain Aβ1–42 [14]. AD-like neurodegeneration "
        "occurs in P. gingivalis-infected neurons that keep active gingipains [48]. "
        "Repeated oral application of a periodontal pathogen in wild-type mice produces "
        "neuroinflammation and Aβ-related changes [15]. P. gingivalis bacteremia "
        "increases endothelial permeability through an Mfsd2a/Caveolin-1 transcytosis "
        "path [49]. Gingipains and outer-membrane vesicles supply vehicles for bacterial "
        "cargo beyond the producing cell [12–13]. Meta-analyses and an AD cohort link "
        "periodontitis to later cognitive decline [9–10]. A two-sample Mendelian "
        "randomization analysis did not support a genetic causal effect [11]. Those "
        "reports supply biological background for examining oral products in AD-related "
        "pathology. They do not assign the twelve peptides to P. gingivalis, and they "
        "do not show that any one string crosses endothelium or accumulates in brain "
        "[7–8,25]. A 7–9-aa peptide is smaller than gingipains or vesicles; size alone "
        "is not evidence of barrier crossing. Charge, proteolysis, plasma binding and "
        "transport all affect exposure, and none of those processes is modelled here. "
        "Docking and MD below address predicted contacts at AChE after an oral "
        "heptapeptide has been placed on the enzyme."
    ),
    "Deep-learning peptide mining supplied the filter stack.": (
        "Deep-learning peptide mining supplied the filter stack. Millions of translated "
        "microbiome open reading frames have been scored before experimental filters "
        "[18]. UniDL4BioPep uses the same predict-then-filter logic on ESM-2 embeddings "
        "[19]. NTxPred2, mebipred and AnOxPePred were trained for neurotoxic, "
        "metal-binding and antioxidant endpoints, not for AChE occupancy [31–33]. "
        "Catalogue matches to HOMD, eHOMD and salivary metaproteomes support prior "
        "observation of a string, as in other oral peptide studies [16,26–30]. A genomic "
        "catalogue hit records coding potential. A metaproteomic hit records a detected "
        "peptide. Neither measurement is host-tissue exposure of the twelve docking "
        "ligands. The serial scores function as a triage stack that nominates "
        "strings for structure work. The twelve docking ligands are 7–9 residues, alkaline, and "
        "net-positive at pH 7.4, with leucine-rich cores. Asp74 and Trp286 form a common "
        "core for peripheral ligands [50], and cationic substrate first docks on Asp74 "
        "[51]. Those physicochemical traits made the twelve strings worth docking. Net "
        "charge and leucine content do not establish PAS selectivity, a shared binding "
        "mode, or affinity."
    ),
    "Human AChE (PDB 4EY6) gives an experimental frame": (
        "Human AChE (PDB 4EY6) gives an experimental frame for the gorge and PAS [22], "
        "following the aromatic-gorge map on Torpedo AChE [23,52]. The 20-Å gorge "
        "couples a catalytic triad at the base to a peripheral cluster at the rim [53]. "
        "AutoDock Vina is a first-pass ranking engine [34–35]. Recurring predicted "
        "contacts fall on the PAS array. FLLHTTR is predicted to hydrogen-bond Asp74, "
        "Tyr72 and His287. YLSLLQR is predicted to bridge Tyr72 and Thr75 at the gorge "
        "mouth. LLHPLRL is predicted to span Trp286 and Tyr341 and reach catalytic "
        "His447. Donepezil in 4EY6 also contacts PAS and the catalytic region [22]; "
        "shared residue names do not make the peptide pose equivalent in mode or "
        "function. HLLTLKKHV reaches Phe346 in the 344–361 zone occupied by Aβ on a "
        "1-μs trajectory [21]. PAS ligands have been crystallised stacked between Trp286 "
        "and Tyr341; the same pair appears for LLHPLRL [54]. ALLLHRC is predicted to "
        "bind catalytic Ser203 and does not contact the outer PAS aromatics. Six of "
        "twelve best poses meet PAS residues. FCLHLQLR, HVLLLRQCA, HLLTLKKHV and "
        "LLHPLRL complete that PAS-contact set; HLPLLHRCC, LLHPLRC, WLLVHLKK and "
        "YHHLLCRR stay off the outer aromatics, and LLHLPKRTT sits adjacent. Contact "
        "with a PAS residue in a docked pose is a predicted geometry. All twelve "
        "ligands were docked. MD was restricted to the three strongest best-run Vina "
        "poses: FLLHTTR and YLSLLQR as PAS-contact poses, ALLLHRC as a high-scoring "
        "catalytic-site pose without outer PAS aromatics, so that PAS geometry could be "
        "compared with a strong non-PAS score. Docking scores put all twelve strings in "
        "a favourable window. The scores are first-pass ranks, not binding constants. "
        "The contact list separates a PAS-contact pose from a catalytic-site pose: "
        "Asp74/Tyr72/Trp286/Tyr341 versus Ser203."
    ),
    "MD studies of AChE–Aβ already treat the enzyme as a nucleation centre.": (
        "MD studies of AChE–Aβ already treat the enzyme as a nucleation centre. "
        "Accelerated sampling pulled Aβ onto the AChE surface [20]. A 1-μs PAS-centred "
        "trajectory remained bound [21]. The present work reports one 100-ns production "
        "trajectory for each of four systems: apo AChE and the ALLLHRC, FLLHTTR and "
        "YLSLLQR complexes. Apo AChE remains a compact hydrolase. ALLLHRC tracks that "
        "control. FLLHTTR and YLSLLQR sit below apo after the first half of the run. "
        "Mean fluctuation is below apo for FLLHTTR and YLSLLQR and slightly above apo "
        "for ALLLHRC. Catalytic-core fluctuations stay low in all four systems. Loop "
        "residues at the gorge rim fluctuate more than the triad, consistent with PAS as "
        "a surface cluster [46,54]. Radius of gyration barely shifts across apo and the "
        "three complexes. Helix and sheet overlay the apo bars, so secondary structure "
        "is not rewritten on this window. Apo AChE is already a stiff α/β hydrolase; the "
        "deep aromatic gorge does not require large domain motion for catalysis [52]. A "
        "small drop in complex compactness relative to that apo baseline is a tightening "
        "of an already compact fold. Lower RMSF on this window records reduced "
        "fluctuation of those atoms. A SASA drop can reflect interface burial or a "
        "global shape change. Solvent-accessible surface rises for ALLLHRC relative to "
        "apo, sits near apo for FLLHTTR, and falls only for YLSLLQR. Intermolecular "
        "hydrogen-bond counts stay high for FLLHTTR through 100 ns, sit lower for "
        "YLSLLQR, and thin out for ALLLHRC. Count is not occupancy or affinity; "
        "occupancy and lifetime were not tabulated. Centre-of-mass distances stay in "
        "the surface-residence range. None of the three peptides left the enzyme on this "
        "window, so the predicted pose persisted in a single 100-ns trajectory. "
        "FLLHTTR keeps a dense intermolecular hydrogen-bond net at PAS. YLSLLQR keeps a "
        "more compact complex. ALLLHRC does not keep a PAS-type network despite a strong "
        "Ser203 docking score. PAS-directed small "
        "molecules can suppress AChE-induced aggregation without catalytic-site "
        "occupancy [6]. The present split is a computational analogue of that "
        "biochemical distinction, limited to one trajectory per complex."
    ),
    "The calculations do not establish a four-step pathogenic cascade.": (
        "Binding at PAS, hindrance of acetylcholine hydrolysis, and modulation of Aβ "
        "nucleation remain separate problems. Only the first is treated here as a "
        "predicted geometry. If a candidate were later shown to bind PAS in vitro, it could change "
        "the local interaction environment of that surface. If the bound pose overlapped "
        "the substrate path, catalytic activity would need a separate assay. The sign of "
        "any effect on Aβ assembly is not given by docking or MD. Because PAS is a "
        "documented pro-fibrillar site [4–5,43], a peptide remaining there could in "
        "principle alter nucleation. A peptide that competed for Aβ-relevant PAS "
        "contacts could also reduce AChE-mediated assembly. Occupancy of a "
        "pro-fibrillar site is compatible with either outcome. PAS-directed small "
        "molecules can block AChE-induced aggregation [6], which is the inhibitory "
        "reading; AChE–Aβ complexes are more toxic than free peptide [4], which is the "
        "promotional reading when the ligand is Aβ itself. An oral heptapeptide is "
        "neither of those ligands. Folded AChE presenting a peptide-coated PAS has been "
        "invoked to explain greater hippocampal damage of AChE–Aβ particles relative to "
        "free fibrils [45]. That literature describes AChE–Aβ complexes, not the "
        "present oral peptides. Peptide–AChE binding, AChE activity and Aβ aggregation "
        "kinetics are required to choose between promotion and inhibition."
    ),
    "PAS pharmacology in AChE has mostly been small molecules.": (
        "PAS pharmacology in AChE has mostly been small molecules. PAS ligands reduce "
        "AChE-induced aggregation without requiring catalytic-site occupancy [6]. "
        "Donepezil in 4EY6 spans PAS Trp286 to the catalytic anionic site, a dual-binding "
        "template mapped on Torpedo AChE [22–23]. That surface has been treated as a "
        "design handle for ligands that modulate heterologous protein associations, "
        "including Aβ [46]. Dual-binding inhibitors were designed to occupy PAS and the "
        "catalytic anionic site at once, with the therapeutic aim of slowing both "
        "acetylcholine hydrolysis and PAS-templated Aβ assembly [44,46]. Short cationic peptides cover a larger patch than those ligands. An oral "
        "heptapeptide that covers only the rim cannot be scored against that dual-binding "
        "template. FLLHTTR and YLSLLQR remain at the rim in the present poses. ALLLHRC "
        "does not, even though all three scored in a favourable docking window. The oral "
        "peptides are computational candidates at a functional surface that already has "
        "experimental support."
    ),
    "The twelve strings come from getorf prediction": (
        "The twelve strings come from getorf prediction, UniDL4BioPep scoring and "
        "catalogue matching on PRJNA678453 MAGs. That pipeline does not prove that every "
        "candidate is expressed in the oral niche or that an intact peptide reaches host "
        "tissue. Docking reports a pose under one scoring function and one AChE crystal "
        "frame; the score is not an experimental Kd. Each MD system is a single 100-ns "
        "trajectory, which cannot map association and dissociation. Repeat runs, "
        "hydrogen-bond occupancy tables and interface-area breakdowns were not the basis "
        "of the present claims. No peptide–AChE binding assay, no AChE activity assay "
        "and no Aβ aggregation assay were performed. In-vivo exposure, plasma stability "
        "and barrier crossing remain unknown. FLLHTTR and YLSLLQR supply the strongest "
        "computational case for predicted PAS contacts that persist on this window. The "
        "work nominates those peptides and a testable hypothesis: oral micropeptides may "
        "interact with AChE-PAS. If a biochemical interaction is confirmed, repeat "
        "simulations and competition experiments can then locate the site and the "
        "functional direction. Later assays of peptide–AChE binding, AChE catalysis "
        "and Aβ aggregation, together with expression and exposure data, are required to "
        "test that hypothesis."
    ),
}

EN_DELETE_PREFIXES: tuple[str, ...] = ()

CN_REPLACE = {
    "AChE 在胆碱能突触水解乙酰胆碱。": (
        "AChE 在胆碱能突触水解乙酰胆碱。AD 组织中，同一酶出现在淀粉样斑块上。"
        "AChE 经 PAS 加速 Aβ 成纤，且 AChE–Aβ 颗粒毒性高于游离肽[4]。"
        "稳定的酶–肽复合物改变 AChE 生化性质并提高纤丝神经毒性。分离得到的复合物中，酶结合的是生长中的纤丝[38–39]。"
        "一段疏水 PAS 基序即足以产生伴侣效应[5]。抗 AChE 单抗可阻断该效应[40]，PAS 导向小分子达到同一终点[6]。"
        "小鼠中过量 AChE 促进皮层 Aβ 斑块[41]。关于 AD 中 AChE 的综述把斑块相关酶放进与 Aβ、磷酸化 tau 的交叉对话，"
        "且斑块相关活性仍对 PAS 阻断敏感[42–44]。海马区 AChE–Aβ 复合物的损伤强于游离纤丝[45]。"
        "PAS 定位于 Tyr72、Asp74、Tyr124、Trp286 和 Tyr341，距峡部底部催化三联体约 20 Å[46]。"
        "这些研究支持 PAS 作为可参与 AChE 介导 Aβ 聚集的功能性表面[2–3]。"
        "本研究的对接与 100 ns 轨迹查看牙周炎来源微肽在该表面上的预测接触。"
    ),
    "口腔暴露路径在菌体和蛋白酶水平已有具体事例。": (
        "口腔暴露路径在菌体和蛋白酶水平已有具体事例。"
        "短期死后 AD 脑组织中已检出牙周致病毒力因子[47]。"
        "AD 脑内已报告 P. gingivalis 与牙龈蛋白酶，小鼠口腔感染升高脑内 Aβ1–42[14]。"
        "持续表达活性牙龈蛋白酶的感染神经元出现 AD 样变性[48]。"
        "野生型小鼠反复口腔给予牙周病原后产生神经炎症和 Aβ 相关改变[15]。"
        "P. gingivalis 菌血症经 Mfsd2a/Caveolin-1 转胞吞路径增加内皮通透性[49]。"
        "牙龈蛋白酶与外膜囊泡可把细菌货物送出产生细胞[12–13]。"
        "综合分析与 AD 队列把牙周炎与后续认知下降联系起来[9–10]。"
        "两样本孟德尔随机化并未支持遗传因果效应[11]。"
        "这些报告为在 AD 相关病理中检查口腔产物提供了生物学背景。"
        "它们不能把 12 条肽归于 P. gingivalis，也不能证明某一字符串穿过内皮或在脑内蓄积[7–8,25]。"
        "7–9 aa 肽比牙龈蛋白酶或囊泡更小；分子更小本身不是屏障穿越的证据。"
        "电荷、蛋白酶降解、血浆结合和转运都会影响暴露，这些过程均未在此建模。"
        "下文对接与 MD 处理的是：口腔七肽被放到 AChE 上之后，预测接触落在何处。"
    ),
    "深度学习肽挖掘提供了此处的过滤栈。": (
        "深度学习肽挖掘提供了此处的过滤栈。"
        "数百万条翻译的微生物组开放阅读框先被打分，再做实验过滤[18]。"
        "UniDL4BioPep 在 ESM-2 嵌入上沿用同一先预测再过滤逻辑[19]。"
        "NTxPred2、mebipred 与 AnOxPePred 分别针对神经毒性、金属结合和抗氧化终点训练，并非针对 AChE 占据[31–33]。"
        "与 HOMD、eHOMD 和唾液宏蛋白质组的目录匹配支持该字符串曾经被观察到，这与其他口腔肽研究中这些资源的角色相同[16,26–30]。"
        "基因组目录命中记录的是编码潜力；宏蛋白质组命中记录的是检出肽。二者都不是 12 条对接配体在宿主组织中的暴露。"
        "串联分数用作分诊栈，把字符串提名到结构分析。"
        "12 条对接配体为 7–9 残基、碱性、pH 7.4 净正电，核心偏亮氨酸。"
        "Asp74 与 Trp286 构成外周配体的共同核心[50]，阳离子底物首先停在 Asp74[51]。"
        "这些理化特征使这 12 条值得对接。净电荷和亮氨酸含量不能证明对 PAS 有选择性，也不能给出统一结合模式或亲和力。"
    ),
    "人源 AChE（PDB 4EY6）为峡部与 PAS 提供实验框架": (
        "人源 AChE（PDB 4EY6）为峡部与 PAS 提供实验框架[22]，沿用电鳗 AChE 上的芳香峡部定位[23,52]。"
        "20 Å 峡部把底部催化三联体与 rim 外周簇耦联[53]。AutoDock Vina 是第一轮排序引擎[34–35]。"
        "反复出现的预测接触落在 PAS 阵列上。"
        "FLLHTTR 预测与 Asp74、Tyr72、His287 形成氢键。YLSLLQR 预测在峡部入口桥接 Tyr72 与 Thr75。"
        "LLHPLRL 预测跨越 Trp286 与 Tyr341 并到达催化 His447。"
        "4EY6 中 donepezil 也接触 PAS 与催化区[22]；残基名称相同，并不使肽构象在模式或功能上等同于该抑制剂。"
        "HLLTLKKHV 到达 1 μs 轨迹中 Aβ 驻留的 344–361 区 Phe346[21]。"
        "PAS 配体曾被结晶在 Trp286 与 Tyr341 之间；LLHPLRL 出现同一对残基[54]。"
        "ALLLHRC 预测结合催化 Ser203，不接触外侧 PAS 芳香残基。"
        "12 个最优构象中有 6 个碰到 PAS 残基。"
        "FCLHLQLR、HVLLLRQCA、HLLTLKKHV 与 LLHPLRL 补全该 PAS 接触组；"
        "HLPLLHRCC、LLHPLRC、WLLVHLKK 与 YHHLLCRR 停在外侧芳香残基之外，LLHLPKRTT 在旁侧。"
        "对接构象中碰到 PAS 残基，是预测几何。"
        "12 条配体均已对接。MD 限于最优单次 Vina 构象中最强的三条："
        "FLLHTTR 与 YLSLLQR 为 PAS 接触构象，ALLLHRC 为不接触外侧 PAS 芳香残基的高分催化位点构象，以便把 PAS 几何与强非 PAS 分数对照。"
        "对接分数把 12 条串放进有利窗口。分数是第一轮排序，不是结合常数，本身并不能把 PAS 接触构象与催化位点构象分开。"
        "分开来自接触名单：Asp74/Tyr72/Trp286/Tyr341 对 Ser203。"
    ),
    "AChE–Aβ 的 MD 已把该酶当作成核中心": (
        "AChE–Aβ 的 MD 已把该酶当作成核中心。加速采样把 Aβ 拉到 AChE 表面[20]。"
        "1 μs、以 PAS 为中心的轨迹保持结合[21]。"
        "本研究每个体系报告一条 100 ns 生产轨迹：apo AChE 以及 ALLLHRC、FLLHTTR、YLSLLQR 复合物。"
        "apo AChE 保持紧凑水解酶。ALLLHRC 跟随该对照。FLLHTTR 与 YLSLLQR 在轨迹后半段落到 apo 之下。"
        "FLLHTTR 与 YLSLLQR 的平均涨落低于 apo，ALLLHRC 略高。四个体系中催化核心涨落都低。"
        "峡部 rim 的 loop 比三联体更活动，符合 PAS 是表面簇[46,54]。"
        "回转半径在 apo 与三个复合物中几乎不动。螺旋与片层与 apo 柱重叠，二级结构在此窗口未被改写。"
        "apo AChE 本已是刚性 α/β 水解酶；深芳香峡部不需要大结构域运动即可催化[52]。"
        "相对该 apo 基线的小幅收紧，是已经紧凑的折叠再收紧。"
        "此窗口上较低的 RMSF 记录的是相应原子涨落减小。"
        "SASA 下降可能来自界面埋藏，也可能来自整体形状变化。"
        "溶剂可及表面在 ALLLHRC 相对 apo 上升，FLLHTTR 接近 apo，仅 YLSLLQR 下降。"
        "分子间氢键计数在 100 ns 内 FLLHTTR 维持较高，YLSLLQR 较低，ALLLHRC 逐渐变稀。"
        "计数不是占有率或亲和力；占有率与持续时间未列表。"
        "质心距离落在表面驻留范围。三条肽在此窗口内均未离开酶，因此预测构象在单条 100 ns 轨迹上得以维持。"
        "FLLHTTR 在 PAS 保持较密的分子间氢键网，YLSLLQR 复合物更紧凑，"
        "ALLLHRC 尽管 Ser203 对接分数强，并未保持 PAS 型网络。"
        "PAS 导向小分子可在不占据催化位点的情况下抑制 AChE 诱导的聚集[6]。"
        "此处分型只是该生化区分的计算类比，且每个复合物仅一条轨迹。"
    ),
    "现有计算不能建立四步致病级联。": (
        "PAS 结合、妨碍乙酰胆碱水解、调节 Aβ 成核仍是不同问题。此处只把第一项作为预测几何来处理。"
        "若候选肽随后在体外被证明结合 PAS，则可能改变该表面的局部相互作用环境。"
        "若结合构象与底物路径重叠，催化活性需要单独测定。"
        "对接和 MD 不能给出对 Aβ 组装的作用方向。"
        "PAS 是已记录的促纤位点[4–5,43]，停在那里的肽原则上可能改变成核；"
        "若肽竞争性占据与 Aβ 相关的 PAS 接触，也可能减弱 AChE 介导的聚集。"
        "占据促纤位点与两种结局都相容。"
        "PAS 导向小分子可阻断 AChE 诱导的聚集[6]，这是抑制读法；"
        "AChE–Aβ 复合物毒性高于游离肽[4]，这是配体为 Aβ 本身时的促进读法。"
        "口腔七肽不是这两类配体。"
        "折叠的 AChE 出示覆肽 PAS，曾被用来解释 AChE–Aβ 颗粒相对游离纤丝更强的海马损伤[45]。"
        "那一文献描述的是 AChE–Aβ 复合物，不是本研究的口腔肽。"
        "肽–AChE 结合、AChE 酶活和 Aβ 聚集动力学，才能在促进与抑制之间作出区分。"
    ),
    "AChE 的 PAS 药理学此前多为小分子。": (
        "AChE 的 PAS 药理学此前多为小分子。PAS 配体在不要求占据催化位点的情况下降低 AChE 诱导的聚集[6]。"
        "4EY6 中的 donepezil 从 PAS Trp286 跨到催化阴离子位点，即电鳗 AChE 上的双结合模板[22–23]。"
        "该表面被当作调节异源蛋白结合（包括 Aβ）的设计把手[46]。"
        "双结合抑制剂被设计成同时占据 PAS 与催化阴离子位点，治疗意图是同时减慢乙酰胆碱水解和 PAS 模板化的 Aβ 组装[44,46]。"
        "只盖住 rim 的口腔七肽不能按该双结合模板打分。"
        "按现有构象，FLLHTTR 与 YLSLLQR 留在 rim。ALLLHRC 不留在 rim，尽管三条都停在有利的对接窗口。"
        "这些口腔肽是已有实验依据的功能性表面上的计算候选。"
    ),
    "这 12 条串来自对 PRJNA678453 MAG": (
        "这 12 条串来自对 PRJNA678453 MAG 的 getorf 预测、UniDL4BioPep 打分和目录匹配。"
        "该流程不能证明每条候选都在口腔微环境中实际表达，也不能证明完整肽到达宿主组织。"
        "对接给出的是一种评分函数和一帧 AChE 晶体下的构象；分数不是实验 Kd。"
        "每个 MD 体系是单条 100 ns 轨迹，不能刻画完整的结合与解离。"
        "重复轨迹、氢键占有率表和界面面积分解不是本文结论的依据。"
        "未做肽–AChE 结合测定、AChE 酶活测定或 Aβ 聚集实验。"
        "体内暴露、血浆稳定性和屏障穿越仍未知。"
        "FLLHTTR 与 YLSLLQR 为预测 PAS 接触在此窗口上得以维持提供了最强的计算依据。"
        "本研究提名这些肽，并提出可检验的假说：口腔微肽可能与 AChE-PAS 相互作用。"
        "若生化相互作用得到确认，再用重复模拟和竞争实验定位作用位点与功能方向。"
        "后续需要肽–AChE 结合、AChE 催化和 Aβ 聚集实验，并结合表达与暴露数据来检验该假说。"
    ),
}

CN_DELETE_PREFIXES: tuple[str, ...] = ()
