# Discussion at Food Chemistry volume (~1800 EN words).
# Keys = prefixes in the a9 English backup / current Chinese body.
# Fact + [n]; no "Author et al. used"; no RMSD/SASA tables.

EN_REPLACE = {
    "AChE hydrolyses acetylcholine at cholinergic synapses.": (
        "AChE hydrolyses acetylcholine at cholinergic synapses. In AD tissue the same "
        "enzyme sits on amyloid plaques. AChE accelerates Aβ fibril growth through the "
        "PAS, and AChE–Aβ particles are more toxic than free peptide [4]. Stable "
        "enzyme–peptide complexes change AChE biochemistry and raise fibril "
        "neurotoxicity; the enzyme binds growing fibrils rather than free monomer "
        "alone [38–39]. A short hydrophobic PAS motif is sufficient for that chaperone "
        "effect [5]. A monoclonal antibody to AChE blocks the effect [40], and "
        "PAS-directed small molecules reach the same endpoint [6]. Excess AChE "
        "promotes cortical Aβ plaques in mice [41]. Reviews of AChE in AD place "
        "plaque-associated enzyme in cross-talk with Aβ and phospho-tau, still "
        "sensitive to PAS blockade [42–44]. Hippocampal AChE–Aβ complexes produce more "
        "damage than free fibrils [45]. The PAS maps to Tyr72, Asp74, Tyr124, Trp286 "
        "and Tyr341, about 20 Å from the catalytic triad at the gorge mouth [46]. "
        "Those experiments identify the PAS as a structural hinge between cholinergic "
        "failure and amyloid deposition [2–3]. The present docking and 100-ns "
        "trajectories examine occupancy of that hinge by periodontitis-derived "
        "micropeptides."
    ),
    "An oral exposure path is already documented": (
        "An oral exposure path is already documented at the organism and protease "
        "level. Periodontopathic virulence factors have been detected in short-term "
        "postmortem AD brain [47]. P. gingivalis and gingipains have been reported in "
        "AD brains, and oral infection in mice raises brain Aβ1–42 [14]. AD-like "
        "neurodegeneration occurs in P. gingivalis-infected neurons that keep active "
        "gingipains [48]. Repeated oral application of a periodontal pathogen in "
        "wild-type mice produces neuroinflammation and Aβ-related changes [15]. "
        "P. gingivalis bacteremia increases endothelial permeability through an "
        "Mfsd2a/Caveolin-1 transcytosis path [49]. Gingipains and outer-membrane "
        "vesicles supply vehicles for bacterial cargo beyond the producing cell "
        "[12–13]. Meta-analyses and an AD cohort link periodontitis to later "
        "cognitive decline [9–10]. A two-sample Mendelian randomization analysis did "
        "not support a genetic causal effect [11]. Those reports justify looking at "
        "oral products at the PAS. Assignment of the twelve peptides to P. gingivalis, "
        "or proof that any one string crosses endothelium, lies outside those reports "
        "[7–8,25]. Gingipains, LPS and vesicles already travel, and a 7–9-aa cationic "
        "peptide is smaller than those cargos. Survival of such a peptide in saliva, "
        "serum and endothelium is outside the present calculation. The docking and MD "
        "below address occupancy of the PAS implicated in fibril growth, given an oral "
        "heptapeptide placed at AChE."
    ),
    "Deep-learning peptide mining supplies the filter stack used here.": (
        "Deep-learning peptide mining supplies the filter stack used here. Millions of "
        "translated microbiome open reading frames have been scored before experimental "
        "filters [18]. UniDL4BioPep uses the same predict-then-filter logic on ESM-2 "
        "embeddings [19]. NTxPred2, mebipred and AnOxPePred were trained for "
        "neurotoxic, metal-binding and antioxidant endpoints, not for AChE occupancy "
        "[31–33]. Catalogue matches to HOMD, eHOMD and salivary metaproteomes support "
        "prior observation of a string, as in other oral peptide studies [16,26–30], "
        "so the serial scores function as a triage stack. The twelve docking ligands "
        "are 7–9 residues, alkaline, and net-positive at pH 7.4, with leucine-rich "
        "cores. That composition matches the electrostatic character of the PAS. Asp74 "
        "and Trp286 form a common core for peripheral ligands [50], and cationic "
        "substrate first docks on Asp74 [51]. A short cationic peptide is a plausible "
        "PAS occupant on chemical grounds, pending a structure."
    ),
    "Human AChE (PDB 4EY6) gives an experimental frame": (
        "Human AChE (PDB 4EY6) gives an experimental frame for the gorge and PAS [22], "
        "following the aromatic-gorge map on Torpedo AChE [23,52]. The 20-Å gorge "
        "couples a catalytic triad at the base to a peripheral cluster at the rim [53]. "
        "AutoDock Vina is a first-pass ranking engine [34–35]. Recurring contacts fall "
        "on the PAS array rather than on a new pocket. FLLHTTR hydrogen-bonds Asp74, "
        "Tyr72 and His287. YLSLLQR bridges Tyr72 and Thr75 at the gorge mouth. "
        "LLHPLRL spans Trp286 and Tyr341 and reaches catalytic His447, the dual "
        "PAS–catalytic geometry of donepezil in 4EY6 [22]. HLLTLKKHV reaches Phe346 in "
        "the 344–361 zone occupied by Aβ on a 1-μs trajectory [21]. PAS ligands have "
        "been crystallised stacked between Trp286 and Tyr341; the same pair appears "
        "for LLHPLRL [54]. ALLLHRC is the exception: it binds catalytic Ser203 and "
        "does not contact the outer PAS aromatics. Six of twelve best poses meet PAS "
        "residues. FCLHLQLR, HVLLLRQCA, HLLTLKKHV and LLHPLRL complete that "
        "PAS-positive set; HLPLLHRCC, LLHPLRC, WLLVHLKK and YHHLLCRR stay off the outer "
        "aromatics, and LLHLPKRTT sits adjacent. The three MD ligands were the "
        "strongest scorers, two of them PAS-positive. Docking scores put all twelve "
        "strings in a favourable window; they are first-pass ranks, not binding "
        "constants, and they do not by themselves distinguish a PAS occupant from a "
        "catalytic-site occupant. That distinction comes from the contact list: "
        "Asp74/Tyr72/Trp286/Tyr341 versus Ser203. FLLHTTR and YLSLLQR belong to the "
        "first group. ALLLHRC belongs to the second. Running MD on both groups "
        "compares a strong docking score with PAS geometry as the requirement for a "
        "lasting complex."
    ),
    "MD studies of AChE–Aβ already treat the enzyme as a nucleation centre.": (
        "MD studies of AChE–Aβ already treat the enzyme as a nucleation centre. "
        "Accelerated sampling pulled Aβ onto the AChE surface [20]. A 1-μs PAS-centred "
        "trajectory remained bound without unfolding the fold [21]. The same occupancy "
        "pattern appears here on a 100-ns window. Apo AChE levels as a compact "
        "hydrolase. ALLLHRC tracks that control. FLLHTTR and YLSLLQR sit below apo "
        "after the first half of the run, which reads as rigidification, not unfolding. "
        "A complex that is more compact than apo is local rigidity after binding. That "
        "reading matches the surface-bound, non-dissociating AChE–Aβ complex [20,21]. "
        "Peptide self-fit compactness ranks the ligands in the same order as PAS "
        "contact: YLSLLQR the most compact on the enzyme, ALLLHRC the most mobile, "
        "FLLHTTR in between. Apo AChE is already a stiff α/β hydrolase; the deep "
        "aromatic gorge does not require large domain motion for catalysis [52]. A "
        "small drop in complex compactness relative to that apo baseline is a "
        "tightening of an already compact fold, short of rebuilding the enzyme. "
        "AChE itself has two jobs on the same fold: feeding the catalytic triad "
        "and templating Aβ at the PAS. That dual role is why a PAS occupant and a "
        "catalytic-site occupant were both sent to MD: a strong pose at Ser203 can "
        "still fail as a chaperone surface."
    ),
    "Mean RMSF is 0.0778 nm": (
        "Mean fluctuation is below apo for FLLHTTR and YLSLLQR and slightly above apo "
        "for ALLLHRC. Catalytic-core fluctuations stay low in all four systems. Loop "
        "residues at the gorge rim fluctuate more than the triad, as expected from the "
        "PAS being a surface cluster rather than a buried pocket [46,54]. PAS binding "
        "has been described as a surface event that need not open the fold; the "
        "fluctuation pattern is that event. Radius of gyration barely shifts across apo "
        "and the three complexes. A shift of that size is spatial accommodation of a "
        "heptapeptide, not unravelling of the α/β hydrolase core. Helix and sheet "
        "overlay the apo bars, so secondary structure is not rewritten on this window. "
        "A more compact complex plus preserved secondary structure has been read as "
        "ligand-induced rigidity at this enzyme [20,21]; the present traces follow "
        "that reading."
    ),
    "Hydrogen-bond histories separate the ligands": (
        "Intermolecular hydrogen bonds separate the ligands more sharply than "
        "compactness. ALLLHRC decays from early occupancy to a thin net by the end of "
        "the window. FLLHTTR holds a dense net for the full 100 ns. YLSLLQR sits "
        "between those extremes. Persistent intermolecular contacts remain in each "
        "complex. Centre-of-mass distances stay in the surface-residence range rather "
        "than bulk solvent. Solvent-accessible surface rises for ALLLHRC relative to "
        "apo, sits near apo for FLLHTTR, and falls only for YLSLLQR. A drop in SASA is "
        "read as a more compact complex; that reading applies to YLSLLQR. FLLHTTR "
        "therefore looks like a hydrogen-bond-rich PAS occupant that rigidifies the "
        "protein without burying extra surface. YLSLLQR looks like a compact PAS "
        "occupant that does bury surface. ALLLHRC, despite a strong docking score on "
        "Ser203, does not leave a lasting PAS-type network. The three complexes "
        "therefore do not tell one story. FLLHTTR is the hydrogen-bond-rich PAS ligand. "
        "YLSLLQR is the compact PAS ligand. ALLLHRC is a catalytic-site scorer that "
        "later loses occupancy. That split is the docking–MD equivalent of the "
        "biochemical split between PAS-directed ligands, which suppress AChE-induced "
        "aggregation, and catalytic-site ligands, which need not [6]. A 1-μs Aβ "
        "trajectory and the present 100-ns peptide trajectories differ in ligand "
        "length and sampling window. Both still show a ligand remaining at the PAS "
        "with the fold closed [21]."
    ),
    "Four linked steps then follow from the cited PAS literature.": (
        "Four linked steps then follow from the cited PAS literature. First, PAS "
        "recognition: occupancy of Asp74, Tyr72, Trp286 and Tyr341 places a "
        "heterologous peptide at the gorge mouth that feeds the catalytic triad, the "
        "first step assigned to cationic substrate at this enzyme [3,22,51]. Second, a "
        "lasting enzyme–peptide complex: intermolecular hydrogen bonds persist, as in "
        "AChE–Aβ trajectories and in isolated stable complexes [20,21,38]. Third, "
        "restricted acetylcholine access: physical blockage at the 20-Å gorge entrance "
        "can hinder substrate even while the catalytic core remains folded, the "
        "steric-blockade mode described for PAS ligands [46,53]. Fourth, pathological "
        "chaperone activity: because the PAS is a documented pro-fibrillar site "
        "[4–5,43], a peptide that remains there can lower the nucleation barrier for "
        "endogenous Aβ. Folded AChE would then present a peptide-coated PAS on which "
        "Aβ oligomers can co-assemble, which accounts for the greater hippocampal "
        "damage of AChE–Aβ particles relative to free fibrils [45]."
    ),
    "PAS pharmacology in AChE has mostly been small molecules.": (
        "PAS pharmacology in AChE has mostly been small molecules. PAS ligands reduce "
        "AChE-induced aggregation without requiring catalytic-site occupancy [6]. "
        "Donepezil in 4EY6 spans PAS Trp286 to the catalytic anionic site, a "
        "dual-binding template mapped on Torpedo AChE [22–23]. That surface has been "
        "treated as a design handle for ligands that modulate heterologous protein "
        "associations, including Aβ [46]. Short cationic peptides occupy a larger "
        "surface than those ligands. The present poses place an oral heptapeptide on "
        "the same aromatic cluster. They are not a claim that the peptides are drugs. "
        "Dual-binding inhibitors were designed to occupy PAS and the catalytic anionic "
        "site at once, with the therapeutic aim of slowing both acetylcholine "
        "hydrolysis and PAS-templated Aβ assembly [44,46]. An oral heptapeptide that "
        "covers only the rim cannot be scored against that dual-binding template. What "
        "FLLHTTR and YLSLLQR can do, on the present evidence, is remain at the rim. "
        "That is the occupancy treated as the chaperone trigger [4], not the longer "
        "dual-binding pose crystallised for donepezil [22]. PAS therefore carries "
        "both a catalytic-access function and a pro-fibrillar function on one "
        "protein. A rim peptide can touch the second without covering the first. "
        "That is why FLLHTTR and YLSLLQR are read as PAS ligands and ALLLHRC is "
        "not, even though all three docked in a favourable window."
    ),
    "On that literature, short, cationic, leucine-rich oral micropeptides": (
        "On that literature, short, cationic, leucine-rich oral micropeptides "
        "predicted from PRJNA678453 MAGs can occupy the experimentally mapped "
        "Aβ-binding PAS and remain there on a 100-ns timescale. A binding assay and an "
        "Aβ-aggregation experiment are still required."
    ),
}

EN_DELETE_PREFIXES: tuple[str, ...] = ()

CN_REPLACE = {
    "牙周炎 MAG 文库筛出的十二条": (
        "AChE 在胆碱能突触水解乙酰胆碱。AD 组织中，同一酶出现在淀粉样斑块上。"
        "AChE 经 PAS 加速 Aβ 成纤，且 AChE–Aβ 颗粒毒性高于游离肽[4]。"
        "稳定的酶–肽复合物改变 AChE 生化性质并提高纤丝神经毒性；酶结合的是生长中的纤丝而非游离单体[38–39]。"
        "一段疏水 PAS 基序即足以产生伴侣效应[5]。抗 AChE 单抗可阻断该效应[40]，PAS 导向小分子达到同一终点[6]。"
        "小鼠中过量 AChE 促进皮层 Aβ 斑块[41]。关于 AD 中 AChE 的综述把斑块相关酶放进与 Aβ、磷酸化 tau 的交叉对话，"
        "且仍对 PAS 阻断敏感[42–44]。海马区 AChE–Aβ 复合物的损伤强于游离纤丝[45]。"
        "PAS 定位于 Tyr72、Asp74、Tyr124、Trp286 和 Tyr341，距峡部底部催化三联体约 20 Å[46]。"
        "这些实验把 PAS 定为胆碱能衰竭与淀粉样沉积之间的结构铰链[2–3]。"
        "本研究的对接与 100 ns 轨迹查看牙周炎来源微肽对该铰链的占据。"
    ),
    "口腔产物到达脑内 AChE 仍是假说": (
        "口腔暴露路径在菌体和蛋白酶水平已有具体事例。"
        "短期死后 AD 脑组织中已检出牙周致病毒力因子[47]。"
        "AD 脑内已报告 P. gingivalis 与牙龈蛋白酶，小鼠口腔感染升高脑内 Aβ1–42[14]。"
        "持续表达活性牙龈蛋白酶的感染神经元出现 AD 样变性[48]。"
        "野生型小鼠反复口腔给予牙周病原后产生神经炎症和 Aβ 相关改变[15]。"
        "P. gingivalis 菌血症经 Mfsd2a/Caveolin-1 转胞吞路径增加内皮通透性[49]。"
        "牙龈蛋白酶与外膜囊泡可把细菌货物送出产生细胞[12–13]。"
        "综合分析与 AD 队列把牙周炎与后续认知下降联系起来[9–10]。"
        "两样本孟德尔随机化并未支持遗传因果效应[11]。"
        "这些报告支持在 PAS 上检查口腔产物。"
        "把 12 条肽归于 P. gingivalis，或证明某一字符串穿过内皮，都不在这些报告之内[7–8,25]。"
        "牙龈蛋白酶、脂多糖和囊泡已经在走，7–9 aa 阳离子肽比这些货物更小。"
        "该肽在唾液、血清和内皮中能否存活，不在本次计算范围内。"
        "下文对接与 MD 处理的是占据：口腔七肽放到 AChE 上时，是否停在与成纤相关的 PAS。"
    ),
    "十二条对接配体为 7–9 残基": (
        "深度学习肽挖掘提供了此处的过滤栈。"
        "数百万条翻译的微生物组开放阅读框先被打分，再做实验过滤[18]。"
        "UniDL4BioPep 在 ESM-2 嵌入上沿用同一先预测再过滤逻辑[19]。"
        "NTxPred2、mebipred 与 AnOxPePred 分别针对神经毒性、金属结合和抗氧化终点训练，并非针对 AChE 占据[31–33]。"
        "与 HOMD、eHOMD 和唾液宏蛋白质组的目录匹配支持该字符串曾经被观察到，这与其他口腔肽研究中这些资源的角色相同[16,26–30]，"
        "因而串联分数用作分诊栈。"
        "12 条对接配体为 7–9 残基、碱性、pH 7.4 净正电，核心偏亮氨酸。该组成与 PAS 的静电性质相符。"
        "Asp74 与 Trp286 构成外周配体的共同核心[50]，阳离子底物首先停在 Asp74[51]。"
        "短阳离子肽在化学上是合理的 PAS 占据者，结构上仍待显示。"
    ),
    "人源 AChE（PDB 4EY6）给出峡部与 PAS 的实验框架": (
        "人源 AChE（PDB 4EY6）为峡部与 PAS 提供实验框架[22]，沿用电鳗 AChE 上的芳香峡部定位[23,52]。"
        "20 Å 峡部把底部催化三联体与 rim 外周簇耦联[53]。AutoDock Vina 是第一轮排序引擎[34–35]。"
        "反复出现的接触落在 PAS 阵列上，而不是新口袋。"
        "FLLHTTR 与 Asp74、Tyr72、His287 形成氢键。YLSLLQR 在峡部入口桥接 Tyr72 与 Thr75。"
        "LLHPLRL 跨越 Trp286 与 Tyr341 并到达催化 His447，即 4EY6 中 donepezil 的 PAS–催化双重几何[22]。"
        "HLLTLKKHV 到达 1 μs 轨迹中 Aβ 驻留的 344–361 区 Phe346[21]。"
        "PAS 配体曾被结晶在 Trp286 与 Tyr341 之间；LLHPLRL 出现同一对残基[54]。"
        "ALLLHRC 是例外：它结合催化 Ser203，不接触外侧 PAS 芳香残基。"
        "12 个最优构象中有 6 个碰到 PAS 残基。"
        "FCLHLQLR、HVLLLRQCA、HLLTLKKHV 与 LLHPLRL 补全该 PAS 阳性组；"
        "HLPLLHRCC、LLHPLRC、WLLVHLKK 与 YHHLLCRR 停在外侧芳香残基之外，LLHLPKRTT 在旁侧。"
        "三条 MD 配体是打分最强者，其中两条 PAS 阳性。"
        "对接分数把 12 条串放进有利窗口；它们是第一轮排序，不是结合常数，本身并不能把 PAS 占据者与催化位点占据者分开。"
        "分开来自接触名单：Asp74/Tyr72/Trp286/Tyr341 对 Ser203。"
        "FLLHTTR 与 YLSLLQR 属前一组。ALLLHRC 属后一组。"
        "对两组都做 MD，是把强对接分数与 PAS 几何并排比较，看持续复合物需要哪一项。"
    ),
    "AChE–Aβ 的 MD 已把该酶当作成核中心": (
        "AChE–Aβ 的 MD 已把该酶当作成核中心。加速采样把 Aβ 拉到 AChE 表面[20]。"
        "1 μs、以 PAS 为中心的轨迹保持结合且不使折叠打开[21]。同一占据模式在此出现在 100 ns 窗口。"
        "apo AChE 保持紧凑水解酶。ALLLHRC 跟随该对照。FLLHTTR 与 YLSLLQR 在轨迹后半段落到 apo 之下，读作变刚而不是去折叠。"
        "复合物比 apo 更紧凑，是结合后局部变刚。该读法与表面结合、不解离的 AChE–Aβ 复合物相符[20,21]。"
        "肽自身紧凑程度给配体排序，与 PAS 接触一致：YLSLLQR 在酶上最紧凑，ALLLHRC 最活动，FLLHTTR 居中。"
        "apo AChE 本已是刚性 α/β 水解酶；深芳香峡部不需要大结构域运动即可催化[52]。"
        "相对该 apo 基线的小幅收紧，是已经紧凑的折叠再收紧，幅度达不到重建酶。"
        "FLLHTTR 与 YLSLLQR 的平均涨落低于 apo，ALLLHRC 略高。四个体系中催化核心涨落都低。"
        "峡部 rim 的 loop 比三联体更活动，符合 PAS 是表面簇而非埋藏口袋[46,54]。"
        "PAS 结合被写成不必打开折叠的表面事件；涨落轨迹与该描述相符。"
        "回转半径在 apo 与三个复合物中几乎不动。这一量级的位移是七肽的空间容纳，不是 α/β 水解酶核心拆开。"
        "螺旋与片层与 apo 柱重叠，二级结构在此窗口未被改写。"
        "更低的复合物波动加上保留的二级结构，被读作配体诱导的变刚；本轨迹沿用该读法[20,21]。"
        "AChE 在同一折叠上同时承担两件事：向催化三联体送底物，以及在 PAS 上模板化 Aβ。"
        "这一双重角色是把 PAS 占据者与催化位点占据者都送进 MD 的原因：Ser203 上的强构象仍可能当不成伴侣表面。"
    ),
    "由此推出四步。": (
        "氢键历史比紧凑程度更能分开配体。ALLLHRC 从早期占据衰减到窗口末期的稀网。"
        "FLLHTTR 全程维持密网。YLSLLQR 介于两者之间。每个复合物都保留持续分子间接触。"
        "质心距离落在表面驻留范围，而不是体相溶剂。"
        "溶剂可及表面在 ALLLHRC 相对 apo 上升，FLLHTTR 接近 apo，仅 YLSLLQR 下降。"
        "SASA 下降可读作更紧凑的复合物；该读法适用于 YLSLLQR。"
        "因此 FLLHTTR 像富氢键的 PAS 占据者，使蛋白变刚但不额外埋藏表面。"
        "YLSLLQR 像紧凑的 PAS 占据者，确实埋藏表面。"
        "ALLLHRC 尽管在 Ser203 上对接分数强，并未留下持续的 PAS 型网络。"
        "三个复合物因此不是同一个故事：FLLHTTR 是富氢键 PAS 配体，YLSLLQR 是紧凑 PAS 配体，"
        "ALLLHRC 是随后失去占据的催化位点高分者。"
        "该分型对应 PAS 导向配体抑制 AChE 诱导聚集、催化位点配体不必如此的生化分型[6]。"
        "1 μs Aβ 轨迹与此处 100 ns 肽轨迹在配体长度和采样窗口上不同。两者都显示配体留在 PAS 上且折叠未打开[21]。"
        "四步机制由上述 PAS 文献推出。第一，PAS 识别：占据 Asp74、Tyr72、Trp286、Tyr341，"
        "把异源肽放在通向催化三联体的峡部入口，即该酶上赋予阳离子底物的第一步[3,22,51]。"
        "第二，持续的酶–肽复合物：分子间氢键持续，与 AChE–Aβ 轨迹以及分离得到的稳定复合物一致[20,21,38]。"
        "第三，乙酰胆碱进入受限：20 Å 峡部入口的物理占据可在催化核心仍折叠时妨碍底物，即 PAS 配体的空间阻断方式[46,53]。"
        "第四，病理性伴侣活性：PAS 是已记录的促纤位点[4–5,43]，停在那里的肽可降低内源 Aβ 的成核壁垒。"
        "折叠的 AChE 于是出示覆肽 PAS，Aβ 寡聚体可在其上共组装，从而解释 AChE–Aβ 颗粒相对游离纤丝更强的海马损伤[45]。"
    ),
    "AChE 的 PAS 药理学此前多为小分子。": (
        "AChE 的 PAS 药理学此前多为小分子。PAS 配体在不要求占据催化位点的情况下降低 AChE 诱导的聚集[6]。"
        "4EY6 中的 donepezil 从 PAS Trp286 跨到催化阴离子位点，即电鳗 AChE 上的双结合模板[22–23]。"
        "该表面被当作调节异源蛋白结合（包括 Aβ）的设计把手[46]。短阳离子肽占据的表面大于这些配体。"
        "此处构象把口腔七肽放在同一芳香簇上。这不是把这些肽写成药物。"
        "双结合抑制剂被设计成同时占据 PAS 与催化阴离子位点，治疗意图是同时减慢乙酰胆碱水解和 PAS 模板化的 Aβ 组装[44,46]。"
        "只盖住 rim 的口腔七肽不能按该双结合模板打分。"
        "按现有证据，FLLHTTR 与 YLSLLQR 能做的是留在 rim。那是被当作伴侣触发的占据[4]，不是 donepezil 结晶的更长双结合构象[22]。"
        "PAS 因此在同一蛋白上既管催化通道，也管促纤。rim 肽可以碰到第二项而不必盖住第一项。"
        "所以 FLLHTTR 与 YLSLLQR 读作 PAS 配体，ALLLHRC 不读作，尽管三条都停在有利的对接窗口。"
    ),
    "综上，从 PRJNA678453 MAG 预测的短、带正电、富亮氨酸口腔微肽": (
        "按上述文献，从 PRJNA678453 MAG 预测的短、带正电、富亮氨酸口腔微肽可以占据实验已定位的 Aβ 结合 PAS，"
        "并在 100 ns 尺度上留在那里。结合测定和 Aβ 聚集实验仍不可少。"
    ),
}

CN_DELETE_PREFIXES: tuple[str, ...] = ()
